add_executable(ir_printer_smoke ir_printer_smoke.cpp)
target_link_libraries(ir_printer_smoke PRIVATE headers)
target_compile_features(ir_printer_smoke PRIVATE cxx_std_17)
target_compile_definitions(ir_printer_smoke PRIVATE EXODUS_UNIT_TEST)
add_test(NAME ir_printer_smoke COMMAND ir_printer_smoke)

add_executable(ir_builder_test ir_builder_test.cpp)
target_link_libraries(ir_builder_test PRIVATE headers)
target_compile_features(ir_builder_test PRIVATE cxx_std_17)
target_compile_definitions(ir_builder_test PRIVATE EXODUS_UNIT_TEST)
add_test(NAME ir_builder_test COMMAND ir_builder_test)

add_executable(test_verifier test_verifier.cpp)
target_link_libraries(test_verifier PRIVATE headers)
target_compile_features(test_verifier PRIVATE cxx_std_17)
target_compile_definitions(test_verifier PRIVATE EXODUS_UNIT_TEST)
add_test(NAME test_verifier COMMAND test_verifier)

add_executable(dce_test dce_test.cpp)
target_link_libraries(dce_test PRIVATE headers)
target_compile_features(dce_test PRIVATE cxx_std_17)
target_compile_definitions(dce_test PRIVATE EXODUS_UNIT_TEST)
add_test(NAME dce_test COMMAND dce_test)

add_executable(dom_test dom_test.cpp)
target_link_libraries(dom_test PRIVATE headers)
target_compile_features(dom_test PRIVATE cxx_std_17)
target_compile_definitions(dom_test PRIVATE EXODUS_UNIT_TEST)
add_test(NAME dom_test COMMAND dom_test)
